ARG NODE_VERSION=latest
FROM node:${NODE_VERSION}


WORKDIR /usr/src/app
COPY . .

ENV NODE_ENV dev

RUN npm update && \
    npm install

# EXPOSE 7002 7002

CMD ["npm", "run", "start:dev"]
